version: 2
#  https://docs.readthedocs.io/en/stable/config-file/v2.html

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"

sphinx:
  configuration: 'docs/source/conf.py'
  fail_on_warning: true

python:
  install:
    - requirements: 'docs/requirements.txt'
    - requirements: 'docs/requirements_extra.txt'
